spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
